// Date: 15/12/2013 16:12:51
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package qdc.cookies.giftbox;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelGiftbox extends ModelBase
{
  //fields
    ModelRenderer giftboxbottom;
    ModelRenderer giftboxlid;
  
  public ModelGiftbox()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      giftboxbottom = new ModelRenderer(this, 0, 0);
      giftboxbottom.addBox(0F, 0F, 0F, 22, 10, 22);
      giftboxbottom.setRotationPoint(-11F, 50F, -11F);
      giftboxbottom.setTextureSize(128, 128);
      giftboxbottom.mirror = true;
      setRotation(giftboxbottom, 0F, 0F, 0F);
      giftboxlid = new ModelRenderer(this, 0, 32);
      giftboxlid.addBox(0F, 0F, 0F, 24, 3, 24);
      giftboxlid.setRotationPoint(-12F, 47F, -12F);
      giftboxlid.setTextureSize(128, 128);
      giftboxlid.mirror = true;
      setRotation(giftboxlid, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    giftboxbottom.render(f5);
    giftboxlid.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,  entity);
  }

public void renderModel(float f) {
    giftboxbottom.render(f);
    giftboxlid.render(f);
	
}



}
