// Date: 16/12/2013 14:11:52
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package qdc.cookies.giftbox;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelGiftbox extends ModelBase
{
  //fields
    ModelRenderer BoxBottom;
  
  public ModelGiftbox()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      BoxBottom = new ModelRenderer(this, 0, 0);
      BoxBottom.addBox(0F, 0F, 0F, 22, 10, 22);
      BoxBottom.setRotationPoint(-11F, 50F, -11F);
      BoxBottom.setTextureSize(128, 128);
      BoxBottom.mirror = true;
      setRotation(BoxBottom, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    BoxBottom.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void renderModel(float f){
	  BoxBottom.render(f); 
	  
  }
  
  
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
